# Generated by Django 3.2.1 on 2021-05-13 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0003_jobs_job_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='job_status',
            field=models.CharField(choices=[('ID', 'Idle'), ('INIT', 'Initiated'), ('PD', 'Pending'), ('ST', 'Started'), ('FI', 'Finished')], default='ID', max_length=4),
        ),
    ]
