# Generated by Django 3.2 on 2021-05-22 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0004_alter_jobs_job_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobs',
            name='training_data_path',
        ),
        migrations.AddField(
            model_name='jobs',
            name='classes',
            field=models.CharField(choices=[('per', 'Person'), ('veh', 'Veh')], default='per', max_length=4),
        ),
        migrations.AddField(
            model_name='jobs',
            name='epoch',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='jobs',
            name='learning_rate',
            field=models.DecimalField(decimal_places=10, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='jobs',
            name='model_type',
            field=models.CharField(choices=[('CLS', 'Classifier'), ('DET', 'Detector')], default='DET', max_length=4),
        ),
        migrations.AddField(
            model_name='jobs',
            name='tensorboard_link',
            field=models.URLField(blank=True),
        ),
    ]
