# Generated by Django 3.2 on 2021-05-22 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0006_alter_jobs_learning_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='model_description',
            field=models.TextField(default='Generic deep learning model'),
        ),
    ]
